version: 2

sources:
  - name: raw
    description: dataset gz_raw_data
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: ventes de GreenWeez
        columns: 
          - name: date_date
            description: date d'achat
          - name: orders_id
            description: identifiant de commande
          - name: products_id
            description: identifiant du produit
          - name: revenue
            description: prix de vente
          - name: quantity
            description: nombre de quantités vendues
      - name: product
        identifier: raw_gz_product
        description: prix d'achats
        columns:
          - name: products_id
            description: identifiant du produit
          - name: purchase_price
            description: prix d'achat
            tests:
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: frais de livraisons
        columns:
          - name: orders_id
            description: identifiant de commande
          - name: shipping_fee
            description: frais d'expédition
          - name: logCost
            description: coût de log
          - name: ship_cost
            description: coût de livraison
            tests:
              - unique
          
